### ISSUE TITLE
redirect conection to fake host

### ISSUE THREAD

**Issue by qiangweihewu** [geovex/tgp#1]
Client couldn't get connected, could be anything wrong with my config? Looking forward to your help, thanks!

Here is the logs on server:
root@abc:/tgp# ./tgp config.toml 
listen: 0.0.0.0:6666
listen: [::]:6666
redirect conection to fake host

here is the config.toml:

```toml
 listen_url = ["0.0.0.0:6666", "[::]:6666"]
 # listen_url = "0.0.0.0:6666" #you can specify one listen address
 ipv6 = true # try IPv6 while connecting to DC
 # path for unix domain socket for getting stats
 # you can get results with socat
 stats_sock = "tgp.stats"
 # optional obfuscation for outgoing connections
 obfuscate = true
 # fallback host for dpi connection probes (optional)
 host = "google.com:443"
 # Global secret can be specified here. And just one user "_" will be configured.
 # (optional)
 #secret = "dd000102030405060708090a0b0c0d0e0f"
 # Set socks5 proxy for egress traffic (optional, disables middleproxy)
 #socks5 = "127.0.0.1:9050"
 # Auth for SOCKS5 (optional)
 # Now empty password is not allowed. because of https://github.com/golang/go/issues/57285
 #socks5_user = "abcd"
 #socks5_pass = "abcd"
 [users]
 1 = "dd000102030405060708090a0b0c028d9d"
 [users.2]
 secret = "dd102893d01415161718191a1b1c1d1e1f"
 socks5_user = "2" # specify auth for user
 socks5_pass = "2"
 [users.3]
 obfuscate = true
 secret = "dd303132333435363738393a3b3c3d3e3f"
 socks5 = "" # override user 3 to direct conneection
 [users.4]
 secret = "dd404142434445464748494a4b4c4d4e4f"
 socks5 = "127.0.0.2:9050" # override to different proxy
 socks5_user = "4"
 socks5_pass = "4"
 #[users.5]
 #secret = "dd505152535455565758595a5b5c5d5e5f"
 #socks5 = "" # direct connection requires for adtag
 #adtag = "0000000000000000000000000000000001"
```
